language: node_js
cache:
  directories:
    - node_modules
  yarn: true
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'
jobs:
  include:
    - stage: format
      script: yarn lint && yarn format && yarn flow
    - stage: test
      script: yarn test
